language: php

php:
  - 5.5
  - 5.6

env:
  - TYPO3_BRANCH=TYPO3_6-2
  - TYPO3_BRANCH=TYPO3_7-0
  - TYPO3_BRANCH=TYPO3_7-1-0
  - TYPO3_BRANCH=master

matrix:
  include:
    - php: 5.3
      env: TYPO3_BRANCH=TYPO3_6-2
    - php: 5.4
      env: TYPO3_BRANCH=TYPO3_6-2
  allow_failures:
    - env: TYPO3_BRANCH=TYPO3_7-0
    - env: TYPO3_BRANCH=TYPO3_7-1-0
    - env: TYPO3_BRANCH=master
  fast_finish: true

before_script:
  - npm install -g grunt-cli
  - npm install
  - cd ..
  - git clone --branch $TYPO3_BRANCH --depth 1 https://github.com/TYPO3/TYPO3.CMS.git typo3_core
  - mv typo3_core/* .
  - composer install
  - mkdir -p uploads typo3temp typo3conf/ext
  - mv media typo3conf/ext/
  - git clone --branch master --depth 1 https://github.com/fabarea/vidi.git typo3conf/ext/vidi
  - export typo3DatabaseName="typo3";
  - export typo3DatabaseHost="localhost";
  - export typo3DatabaseUsername="root";
  - export typo3DatabasePassword="";

script:
  - cd typo3conf/ext/media && grunt build && cd ../../../
  - ./bin/phpunit -c typo3conf/ext/media/Tests/Build/UnitTests.xml
  - ./bin/phpunit -c typo3conf/ext/media/Tests/Build/FunctionalTests.xml
