<?php

/*********************************************************************
* Extension configuration file for ext "media".
*
* Generated by ext 15-09-2014 09:52 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Media management',
  'description' => 'Media management system for TYPO3 CMS.',
  'category' => 'misc',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '3.0.0',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.2.0-6.2.99',
      'vidi' => '',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
      'metadata' => '',
      'filemetadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'TYPO3 CMS 6.2 compatibility. Change log http://forge.typo3.org/versions/2627',
);

?>