<?php

/*********************************************************************
* Extension configuration file for ext "media".
*
* Generated by ext 02-01-2014 09:06 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Media management',
  'description' => 'Media management system for TYPO3 CMS.',
  'category' => 'misc',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '3.0.0-dev',
  'constraints' => 
  array (
    'depends' => 
    array (
      'cms' => '',
      'extbase' => '',
      'fluid' => '',
      'vidi' => '',
      'typo3' => '6.1.6-6.1.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
      'metadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'Change log http://forge.typo3.org/projects/extension-media/versions/2470',
);

?>