<?php

/*********************************************************************
* Extension configuration file for ext "media".
*
* Generated by ext 09-04-2014 14:20 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'Media management',
  'description' => 'Media management system for TYPO3 CMS.',
  'category' => 'misc',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@typo3.org',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'beta',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '2.0.2',
  'constraints' => 
  array (
    'depends' => 
    array (
      'cms' => '',
      'extbase' => '',
      'fluid' => '',
      'vidi' => '0.0.0-0.3.99',
      'typo3' => '6.1.6-6.1.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
      'metadata' => '',
    ),
  ),
  'user' => 'fab1en',
  'comment' => 'Various fixes for IE 11 and RTE integration. This release was sponsored by http://www.web-vision.de/',
);

?>